### PR TITLE
Refactored code for improved readability and maintainability

### PR DESCRIPTION
**Pull request by german-Luna**
Encapsulated repetitive actions into methods for better organization and reusability.
Modified navigation toolbar setup to handle cases where there's no current tab.
Added if __name__ == "__main__": block to ensure the script runs only when executed directly.
Removed redundant imports and ensured consistent naming conventions for methods and variables.

### CODE REVIEW

**Comment by german-Luna** [comment]
I'm sorry, I forgot the docstrings in this commit

**Comment by german-Luna** [comment]
I'm sorry for all the spam, I never used GitHub this exessive

**Comment by german-Luna** [comment]
If you'd like to merge my modifactions to your repo, just comment here.
Or message me on discord, my tag is "luna_but_bi"

**Comment by Guesty000** [comment]
Yea I would like to merge ur modifications to my repo.

**Pull request closed without merging**
